### PR TITLE
Update to latest version of NewpipeExtractor

### PR DESCRIPTION
**Pull request by wb9688**
I've updated NewpipeExtractor to the latest version.

### CODE REVIEW

**Comment by TheAssassin** [comment]
So, if you "just" updated the extractor submodule, what's all the other files then? Committed by accident? Please elaborate.

**Comment by wb9688** [comment]
There have been some changes in the extractor, which required those changes.

**Comment by TheAssassin** [comment]
Hm, okay. I am just a fan of detailed commit messages. Without them, it's really hard even for yourself to see the reason for a change you made in the past. Please include more details next time.

Furthermore, I am a defendant of atomic commits. Yours includes a bit too much for being a "single change". See also https://sethrobertson.github.io/GitBestPractices/

**Comment by theScrabi** [comment]
Well i think It's ok that way. I'm on holliday  right now. When  I come back I'll merge.

**Comment by wb9688** [comment]
Can't this be merged?

**Comment by TheAssassin** [comment]
@wb9688 please be a bit more patient.

**Comment by wb9688** [comment]
@TheAssassin: I'm patient, I just thought maybe you guys forgot.

**Comment by theScrabi** [comment]
The last append sorry xD

**Pull request merged**
